// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieWebsite.Movies.Models.Databases;

namespace MovieWebsite.Movies.Migrations
{
    [DbContext(typeof(CompositionContext))]
    partial class CompositionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MovieWebsite.Movies.Models.Compositions.Character", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullOriginalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PosterId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("MovieWebsite.Movies.Models.Compositions.DbComposition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PosterId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("DbComposition");

                    b.HasDiscriminator<string>("Discriminator").HasValue("DbComposition");
                });

            modelBuilder.Entity("MovieWebsite.Movies.Models.Compositions.Person", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullOriginalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<long>("PosterId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("MovieWebsite.Movies.Models.Databases.Joins.BookCharacter", b =>
                {
                    b.Property<long>("BookId")
                        .HasColumnType("bigint");

                    b.Property<long>("CharacterId")
                        .HasColumnType("bigint");

                    b.HasKey("BookId", "CharacterId");

                    b.HasIndex("CharacterId");

                    b.ToTable("BookCharacter");
                });

            modelBuilder.Entity("MovieWebsite.Movies.Models.Databases.Joins.MovieCharacter", b =>
                {
                    b.Property<long>("CharacterId")
                        .HasColumnType("bigint");

                    b.Property<long>("MovieId")
                        .HasColumnType("bigint");

                    b.HasKey("CharacterId", "MovieId");

                    b.HasIndex("MovieId");

                    b.ToTable("MovieCharacter");
                });

            modelBuilder.Entity("MovieWebsite.Movies.Models.Databases.Joins.MoviePerson", b =>
                {
                    b.Property<long>("MovieId")
                        .HasColumnType("bigint");

                    b.Property<long>("PersonId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MovieId1")
                        .HasColumnType("bigint");

                    b.HasKey("MovieId", "PersonId");

                    b.HasIndex("MovieId1");

                    b.HasIndex("PersonId");

                    b.ToTable("MoviePerson");
                });

            modelBuilder.Entity("MovieWebsite.Movies.Models.Databases.Joins.PersonBook", b =>
                {
                    b.Property<long>("BookId")
                        .HasColumnType("bigint");

                    b.Property<long>("PersonId")
                        .HasColumnType("bigint");

                    b.HasKey("BookId", "PersonId");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonBook");
                });

            modelBuilder.Entity("MovieWebsite.Movies.Models.Databases.Joins.PersonCharacter", b =>
                {
                    b.Property<long>("CharacterId")
                        .HasColumnType("bigint");

                    b.Property<long>("PersonId")
                        .HasColumnType("bigint");

                    b.HasKey("CharacterId", "PersonId");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonCharacter");
                });

            modelBuilder.Entity("MovieWebsite.Movies.Models.Databases.Joins.PersonSerial", b =>
                {
                    b.Property<long>("PersonId")
                        .HasColumnType("bigint");

                    b.Property<long>("SerialId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SerialId1")
                        .HasColumnType("bigint");

                    b.HasKey("PersonId", "SerialId");

                    b.HasIndex("SerialId");

                    b.HasIndex("SerialId1");

                    b.ToTable("PersonSerial");
                });

            modelBuilder.Entity("MovieWebsite.Movies.Models.Databases.Joins.SerialCharacter", b =>
                {
                    b.Property<long>("CharacterId")
                        .HasColumnType("bigint");

                    b.Property<long>("SerialId")
                        .HasColumnType("bigint");

                    b.HasKey("CharacterId", "SerialId");

                    b.HasIndex("SerialId");

                    b.ToTable("SerialCharacter");
                });

            modelBuilder.Entity("MovieWebsite.Movies.Models.Databases.Rating", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CompositionId")
                        .HasColumnType("bigint");

                    b.Property<long>("DbCompositionId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DbCompositionId");

                    b.ToTable("Rating");
                });

            modelBuilder.Entity("MovieWebsite.Movies.Models.Compositions.Book", b =>
                {
                    b.HasBaseType("MovieWebsite.Movies.Models.Compositions.DbComposition");

                    b.Property<float>("AverageRating")
                        .HasColumnType("real");

                    b.HasDiscriminator().HasValue("Book");
                });

            modelBuilder.Entity("MovieWebsite.Movies.Models.Compositions.Movie", b =>
                {
                    b.HasBaseType("MovieWebsite.Movies.Models.Compositions.DbComposition");

                    b.Property<float>("AverageRating")
                        .HasColumnType("real")
                        .HasColumnName("Movie_AverageRating");

                    b.HasDiscriminator().HasValue("Movie");
                });

            modelBuilder.Entity("MovieWebsite.Movies.Models.Compositions.Serial", b =>
                {
                    b.HasBaseType("MovieWebsite.Movies.Models.Compositions.DbComposition");

                    b.Property<float>("AverageRating")
                        .HasColumnType("real")
                        .HasColumnName("Serial_AverageRating");

                    b.HasDiscriminator().HasValue("Serial");
                });

            modelBuilder.Entity("MovieWebsite.Movies.Models.Databases.Joins.BookCharacter", b =>
                {
                    b.HasOne("MovieWebsite.Movies.Models.Compositions.Book", "Book")
                        .WithMany("BookCharacters")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MovieWebsite.Movies.Models.Compositions.Character", "Character")
                        .WithMany("BookCharacters")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Character");
                });

            modelBuilder.Entity("MovieWebsite.Movies.Models.Databases.Joins.MovieCharacter", b =>
                {
                    b.HasOne("MovieWebsite.Movies.Models.Compositions.Character", "Character")
                        .WithMany("MovieCharacters")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MovieWebsite.Movies.Models.Compositions.Movie", "Movie")
                        .WithMany("MovieCharacters")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieWebsite.Movies.Models.Databases.Joins.MoviePerson", b =>
                {
                    b.HasOne("MovieWebsite.Movies.Models.Compositions.Movie", "Movie")
                        .WithMany("MovieDirectors")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MovieWebsite.Movies.Models.Compositions.Movie", null)
                        .WithMany("MovieActors")
                        .HasForeignKey("MovieId1");

                    b.HasOne("MovieWebsite.Movies.Models.Compositions.Person", "Person")
                        .WithMany("PersonMovies")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("MovieWebsite.Movies.Models.Databases.Joins.PersonBook", b =>
                {
                    b.HasOne("MovieWebsite.Movies.Models.Compositions.Book", "Book")
                        .WithMany("BookAuthors")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MovieWebsite.Movies.Models.Compositions.Person", "Person")
                        .WithMany("PersonBooks")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("MovieWebsite.Movies.Models.Databases.Joins.PersonCharacter", b =>
                {
                    b.HasOne("MovieWebsite.Movies.Models.Compositions.Character", "Character")
                        .WithMany("PersonCharacters")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MovieWebsite.Movies.Models.Compositions.Person", "Person")
                        .WithMany("PersonCharacters")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("MovieWebsite.Movies.Models.Databases.Joins.PersonSerial", b =>
                {
                    b.HasOne("MovieWebsite.Movies.Models.Compositions.Person", "Person")
                        .WithMany("PersonSerials")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MovieWebsite.Movies.Models.Compositions.Serial", "Serial")
                        .WithMany("ActorSerials")
                        .HasForeignKey("SerialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MovieWebsite.Movies.Models.Compositions.Serial", null)
                        .WithMany("PersonSerials")
                        .HasForeignKey("SerialId1");

                    b.Navigation("Person");

                    b.Navigation("Serial");
                });

            modelBuilder.Entity("MovieWebsite.Movies.Models.Databases.Joins.SerialCharacter", b =>
                {
                    b.HasOne("MovieWebsite.Movies.Models.Compositions.Character", "Character")
                        .WithMany("SerialCharacters")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MovieWebsite.Movies.Models.Compositions.Serial", "Serial")
                        .WithMany("SerialCharacters")
                        .HasForeignKey("SerialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Serial");
                });

            modelBuilder.Entity("MovieWebsite.Movies.Models.Databases.Rating", b =>
                {
                    b.HasOne("MovieWebsite.Movies.Models.Compositions.DbComposition", "DbComposition")
                        .WithMany("Ratings")
                        .HasForeignKey("DbCompositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DbComposition");
                });

            modelBuilder.Entity("MovieWebsite.Movies.Models.Compositions.Character", b =>
                {
                    b.Navigation("BookCharacters");

                    b.Navigation("MovieCharacters");

                    b.Navigation("PersonCharacters");

                    b.Navigation("SerialCharacters");
                });

            modelBuilder.Entity("MovieWebsite.Movies.Models.Compositions.DbComposition", b =>
                {
                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("MovieWebsite.Movies.Models.Compositions.Person", b =>
                {
                    b.Navigation("PersonBooks");

                    b.Navigation("PersonCharacters");

                    b.Navigation("PersonMovies");

                    b.Navigation("PersonSerials");
                });

            modelBuilder.Entity("MovieWebsite.Movies.Models.Compositions.Book", b =>
                {
                    b.Navigation("BookAuthors");

                    b.Navigation("BookCharacters");
                });

            modelBuilder.Entity("MovieWebsite.Movies.Models.Compositions.Movie", b =>
                {
                    b.Navigation("MovieActors");

                    b.Navigation("MovieCharacters");

                    b.Navigation("MovieDirectors");
                });

            modelBuilder.Entity("MovieWebsite.Movies.Models.Compositions.Serial", b =>
                {
                    b.Navigation("ActorSerials");

                    b.Navigation("PersonSerials");

                    b.Navigation("SerialCharacters");
                });
#pragma warning restore 612, 618
        }
    }
}
