namespace MovieWebsite.Shared
{
    public enum Genre : ushort
    {
        Action,
        Adventure,
        Comedy,
        Crime,
        Fantasy,
        Historical,
        HistoricalFiction,
        Horror,
        Romance,
        Satire,
        ScienceFiction, 
        Cyberpunk,
        Speculative,
        Thriller,
        Western,
        Political,
        Drama,
        Sports,
        Military,
        Anime,
        SliceOfLife,
        Magic,
        Supernatural,
        Psychological,
        Japanese
    }
}